export { default as UseFloatingBasicUsage } from "./UseFloatingBasicUsage.vue"
export { default as WithMiddleware } from "./WithMiddleware.vue"
export { default as PlacementDemo } from "./PlacementDemo.vue"
export { default as InteractiveTooltip } from "./InteractiveTooltip.vue"
export { default as DropdownMenu } from "./DropdownMenu.vue"
export { default as ModalDialog } from "./ModalDialog.vue"
export { default as Interaction } from "./Interaction.vue"
export { default as ClientPointDemo } from "./ClientPointDemo.vue"
